executable = /home/yuenchen/gender-bias/code/run_test.sh
arguments = $(model)
error = /home/yuenchen/gender-bias/logs/pipeline_$(model).err
output = /home/yuenchen/gender-bias/logs/pipeline_$(model).out
log = /home/yuenchen/gender-bias/logs/pipeline_$(model).log
request_memory = 32G
request_disk = 32G
request_cpus = 1
request_gpus = 1
requirements = TARGET.CUDAGlobalMemoryMb  > 32000


# Queue jobs for each model
queue model in gemma-7b-instruct

