executable = /home/yuenchen/gender-bias/code/run_pipeline.sh
arguments = $(type) $(model)
error = /home/yuenchen/gender-bias/pipeline_copy_mistral.err
output = /home/yuenchen/gender-bias/pipeline_copy_mistral.out
log = /home/yuenchen/gender-bias/pipeline_copy_mistral.log
request_memory = 16G
request_disk = 20G
request_cpus = 1
request_gpus = 1
requirements = TARGET.CUDAGlobalMemoryMb  > 16000
queue type, model from (
    genderquestion_ llama3-70b
    genderquestion_ llama3-70b-instruct
)
